name: Build & Push (A1111 Jupyter Plus)

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'start.sh'
      - 'start-extra.sh'
      - '.github/workflows/build.yml'
  workflow_dispatch:   # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/a1111-jupyter-plus:latest
            ghcr.io/${{ github.repository_owner }}/a1111-jupyter-plus:sha-${{ github.sha }}
